# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-10-26 15:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classes',
            fields=[
                ('classes_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('classes_name', models.CharField(max_length=20)),
                ('students_sum', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='College',
            fields=[
                ('college_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('college_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('course_id', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('course_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('stu_no', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('stu_name', models.CharField(max_length=20)),
                ('stu_age', models.IntegerField()),
                ('stu_tel', models.CharField(max_length=11)),
                ('classes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Classes')),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.College')),
                ('course', models.ManyToManyField(to='app.Course')),
            ],
        ),
        migrations.CreateModel(
            name='Teachers',
            fields=[
                ('teachers_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('teachers_name', models.CharField(max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='teachers',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Teachers'),
        ),
        migrations.AddField(
            model_name='classes',
            name='teachers',
            field=models.ManyToManyField(to='app.Teachers'),
        ),
    ]
