# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-10-25 13:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('name', models.CharField(max_length=30)),
                ('id', models.CharField(max_length=30, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Foods',
            fields=[
                ('name', models.CharField(max_length=30)),
                ('id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('price', models.IntegerField()),
                ('sum', models.IntegerField()),
                ('cls', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.Class')),
            ],
        ),
        migrations.CreateModel(
            name='Ingre',
            fields=[
                ('name', models.CharField(max_length=30, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Production',
            fields=[
                ('name', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('addr', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='foods',
            name='ingre',
            field=models.ManyToManyField(to='goods.Ingre'),
        ),
        migrations.AddField(
            model_name='foods',
            name='production',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.Production'),
        ),
    ]
